name = "westworld-mc-blog"
compatibility_date = "2023-10-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production]
pages.kv_namespaces = [
  { binding = "blog_data", id = "你的CF KV命名空间ID" } # 只保留你的KV ID
]
