name = "westworld-mc-blog"
compatibility_date = "2023-10-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"  # 补这个关键配置，解决无效提示

[pages]
dir = "dist"
branch = "main"

[pages.kv_namespaces]
blog_data = "你的CF KV命名空间ID" # 别删你的ID！

[env.production]
pages.kv_namespaces = [
  { binding = "blog_data", id = "你的CF KV命名空间ID" }
]
